### ISSUE TITLE
Importing a single module does not work

### ISSUE THREAD

**Issue by AlexW-Valtech** [contentstack/cli#61]
If you try to import just a single module rather than all modules, you will get the following error:

```
(node:13856) UnhandledPromiseRejectionWarning: ReferenceError: stackDetails is not defined
    at C:\Users\...\AppData\Roaming\npm\node_modules\@contentstack\cli\node_modules\@contentstack\cli-cm-import\src\app.js:68:9
    at new Promise (<anonymous>)
    at singleImport (C:\Users\...\AppData\Roaming\npm\node_modules\@contentstack\cli\node_modules\@contentstack\cli-cm-import\src\app.js:65:10)
    at C:\Users\...\AppData\Roaming\npm\node_modules\@contentstack\cli\node_modules\@contentstack\cli-cm-import\src\app.js:40:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This appears to be because there is a still a reference to the `stackDetails` function in the mentioned `app.js` file, but that function itself has been removed in a previous commit.

Use the following command to test against some exported content:

`csdx cm:import -A -m content-types`

**Comment by shafeeqd959** [comment]
This is fixed on the latest version of CLI 1.0.3, thanks
